
CREATE TABLE STUDENT(
S_ID BIGINT PRIMARY KEY,
S_NAME VARCHAR(40) NOT NULL
);


CREATE TABLE TEACHER(
T_EMAIL VARCHAR(50) PRIMARY KEY,
T_NAME VARCHAR(40) NOT NULL
);



CREATE TABLE BOOK (
BOOKID VARCHAR(20) PRIMARY KEY,
TITLE VARCHAR(20) NOT NULL,
LINK VARCHAR(150) NOT NULL
);




CREATE TABLE COURSE_RESOURCES (
    RESOURCE_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    COURSE_NAME VARCHAR(100),
    RESOURCE_TYPE VARCHAR(50),
    RESOURCE_LINK VARCHAR(255) NOT NULL,
    FOREIGN KEY (COURSE_NAME, RESOURCE_TYPE)
        REFERENCES COURSE_RESOURCE_TYPES (COURSE_NAME, RESOURCE_TYPE)
        ON DELETE CASCADE
);


CREATE TABLE COURSE_RESOURCE_TYPES (
    COURSE_NAME VARCHAR(100),
    RESOURCE_TYPE VARCHAR(50),
    PRIMARY KEY (COURSE_NAME, RESOURCE_TYPE)
);

CREATE TABLE BORROWBOOK (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BOOK_ID VARCHAR(20),
    USER_ID BIGINT,
    BORROW_DATE DATE,
    RETURN_DATE DATE,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOKID),
    FOREIGN KEY (USER_ID) REFERENCES STUDENT(S_ID)
);



INSERT INTO STUDENT VALUES (1234567890, 'GHUYOOD');
INSERT INTO STUDENT VALUES (1122334455, 'RAGAD');
INSERT INTO STUDENT VALUES (2233445566, 'NOURA');
INSERT INTO STUDENT VALUES (3344556677, 'LAYAN');
INSERT INTO STUDENT VALUES (3344556688, 'MIAD');


INSERT INTO TEACHER VALUES ('ghuyood@iau.edu.sa', 'MAHA');
INSERT INTO TEACHER VALUES ('ragad@iau.edu.sa', 'RAGAD');
INSERT INTO TEACHER VALUES ('noura@iau.edu.sa', 'NOURA');
INSERT INTO TEACHER VALUES ('layan@iau.edu.sa', 'LAYAN');
INSERT INTO TEACHER VALUES ('miad@iau.edu.sa', 'MIAD');

-- AI
INSERT INTO BOOK VALUES ('AI1', 'AI Basics', 'AI1.PNG');
INSERT INTO BOOK VALUES ('AI2', 'Machine Learning', 'AI2.PNG');
INSERT INTO BOOK VALUES ('AI3', 'Deep Learning', 'AI3.JPG');
INSERT INTO BOOK VALUES ('AI4', 'Neural Networks', 'AI4.jpeg');
INSERT INTO BOOK VALUES ('AI5', 'AI Ethics', 'AI5.JPG');
INSERT INTO BOOK VALUES ('AI6', 'AI Tools', 'AI6.JPG');

-- Cyber Security
INSERT INTO BOOK VALUES ('CY1', 'Intro to Security', 'CY1.PNG');
INSERT INTO BOOK VALUES ('CY2', 'Encryption', 'CY2.PNG');
INSERT INTO BOOK VALUES ('CY3', 'Firewalls', 'CY3.JPG');
INSERT INTO BOOK VALUES ('CY4', 'Threat Analysis', 'CY4.JPG');
INSERT INTO BOOK VALUES ('CY5', 'Ethical Hacking', 'CY5.JPG');
INSERT INTO BOOK VALUES ('CY6', 'Network Security', 'CY6.JPG');

-- Calculus
INSERT INTO BOOK VALUES ('CAL1', 'Limits', 'cal1.png');
INSERT INTO BOOK VALUES ('CAL2', 'Derivatives', 'cal2.png');
INSERT INTO BOOK VALUES ('CAL3', 'Integrals', 'cal3.JPG');
INSERT INTO BOOK VALUES ('CAL4', 'Series', 'cal4.JPG');
INSERT INTO BOOK VALUES ('CAL5', 'Applications', 'cal5.JPG');
INSERT INTO BOOK VALUES ('CAL6', 'Multivariable', 'cal6.JPG');

-- OOP
INSERT INTO BOOK VALUES ('OOP1', 'Classes', 'JV1.PNG');
INSERT INTO BOOK VALUES ('OOP2', 'Objects', 'JV2.PNG');
INSERT INTO BOOK VALUES ('OOP3', 'Inheritance', 'JV3.JPG');
INSERT INTO BOOK VALUES ('OOP4', 'Polymorphism', 'JV4.JPG');
INSERT INTO BOOK VALUES ('OOP5', 'Abstraction', 'JV5.JPG');
INSERT INTO BOOK VALUES ('OOP6', 'Encapsulation', 'JV6.JPG');

-- Statistics
INSERT INTO BOOK VALUES ('ST1', 'Data Types', 'ST1.PNG');
INSERT INTO BOOK VALUES ('ST2', 'Probability', 'ST2.PNG');
INSERT INTO BOOK VALUES ('ST3', 'Distributions', 'ST3.JPG');
INSERT INTO BOOK VALUES ('ST4', 'Hypothesis Testing', 'ST4.JPG');
INSERT INTO BOOK VALUES ('ST5', 'Regression', 'ST5.JPG');
INSERT INTO BOOK VALUES ('ST6', 'ANOVA', 'ST6.JPG');

-- Network
INSERT INTO BOOK VALUES ('NT1', 'Intro to Networking', 'NT1.PNG');
INSERT INTO BOOK VALUES ('NT2', 'OSI Model', 'NT2.PNG');
INSERT INTO BOOK VALUES ('NT3', 'IP Addressing', 'NT3.JPG');
INSERT INTO BOOK VALUES ('NT4', 'Routing', 'NT4.JPG');
INSERT INTO BOOK VALUES ('NT5', 'Switching', 'NT5.JPG');
INSERT INTO BOOK VALUES ('NT6', 'Protocols', 'NT6.JPG');

